### PR TITLE
wip - statsd support

### PR DESCRIPTION
**Pull request by gorsuch**
Starting to sketch out a very general statsd publisher, although I don't want to land this until we can figure out https://github.com/canaryio/canary/issues/36.

### CODE REVIEW

**Comment by gorsuch** [comment]
Will pick this up once #42 makes it in.

**Comment by gorsuch** [comment]
rebased against #42 to get those changes here.

**Comment by blkperl** [comment]
Any update? I'm eager to use this :)

**Comment by gorsuch** [comment]
Yay!  I would like to see this land by the end of the weekend.

**Comment by gorsuch** [comment]
Also, any pointers you can give as to how you plan on using this would be much appreciated.

**Comment by blkperl** [comment]
@gorsuch can you update the README to include docs for this publisher?

**Pull request merged**
